### ISSUE TITLE
Odd annotations for document 105

### ISSUE THREAD

**Issue by johann-petrak** [linkedtv/videocorpus#1]
When trying to match the annotations in the gold*.csv files against the files in rbb150/subs/,
there are a number of rows in each of the CSV files where the offsets are larger than the document size, and the "surface form" field is empty. 

For the goldfull.csv file there are 12 such rows. They all also have empty surface forms and seem to be artefacts from previous rows, e.g. these incorrect entries:
```
105,2902,2908,,Person,NIL,
105,3355,3361,,Person,NIL,
105,4195,4201,,Person,NIL,
```
have the same lengths and distances between them as these:
``` 
105,617,623,Gilles,Person,NIL,
105,1070,1076,Gilles,Person,NIL,
105,1910,1916,Gilles,Person,NIL,
```
I think these rows are safe to ignore, but it may be useful to know about them.

**Comment by rtroncy** [comment]
Thanks for raising the issue. @adib2011 are you still working on it? / cc @lyndonnixon

**Comment by adib2011** [comment]
@rtroncy @johann-petrak Yes. Will update it soon. Checking the whole corpus now.

**Comment by adib2011** [comment]
@johann-petrak cc @rtroncy @lyndonnixon fixed the gold standards in csv. It looks like the issue was a bit more complicated. Some entries in the gold standard were doubled and had two additional issues a) no surface form; b) positions outside the document (if you check the document 105 it had only 2285 characters including spaces, therefore positions outside range were not legit). Fixed across all documents (including in the gold standard that contains NILs).
